### ISSUE TITLE
Define environment variables as YAML map in manifest file

### ISSUE THREAD

**Issue by marcmo** [esrlabs/northstar#100]

**Comment by flxo** [comment]
Think this was about changing the manifest format to use a map instead of an array.

**Comment by bzld** [comment]
Yes, the normal YAML style would be this:
```yaml
env:
   HELLO: north
   FOO: bar
```
instead of the current:
```yaml
env: [[HELLO, north], [FOO, bar]
```
