### ISSUE TITLE
Make bind-mounts from host explicit in container manifest

### ISSUE THREAD

**Issue by bzld** [esrlabs/northstar#102]
Currently, we magically bind-mount `/lib` (and `/lib64` if present) on vanilla Linux, and `/system` on Android into the container, and assume that this works out fine.
But that actually creates a hidden dependency between container and supported host - the following things break:
- A fully self-contained NPK (like a Docker image) which contains its own `/lib` or `/lib64` will break because its files in `/lib` will be hidden by the bind-mounted contents from the host, which might also be incompatible with the container binaries. For example turning a minimal Alpine-Linux musl (docker) container into a NPK can break because of different libc.
- Containers built with Android toolchain (expecting linker in `/system/lib` etc.) will try to start on a non-Android host and then fail because of missing host directories, and vice-versa. It would be nicer to detect this problem at installation time already.

Also, this whole bind-mounted /lib approach will break with firecracker, which doesn't support host filesystem sharing at all.

Proposal:
- By default, containers should not bind-mount any real host directory.
- Self-contained NPKs should just work then.
- Non-self contained NPK can either
-- use a (potentially shared) resource container containing `/lib` (and other directories), or
-- explicitly bind-mount folders from the host, which the runtime can check for existence before start

(It's also nicer from a security perspective to see which host files are exposed to containers in the manifest)

Manifest syntax ideas:
```yaml
...
resources:
  - name: ferris
    version: 0.0.2
    dir: /
    mountpoint: /bin
  - name: hello_message
    version: 0.1.2
    dir: /
    mountpoint: /message
host_resources:
  - host_dir: /lib64
  - host_dir: /some/other/lib
    mountpoint: /lib
```

Or maybe a more powerful generic `mounts` similar to docker compose?
```yaml
...
resources:
  - name: ferris
    version: 0.0.2
    dir: /
    mountpoint: /bin
  - name: hello_message
    version: 0.1.2
    dir: /
    mountpoint: /message
mounts:
  - source: /lib64 
    target: /lib64
    type: bind
  - source: /cache 
    target: /cache1
    type: bind
    options: ro
  - source: tmpfs 
    target: /cache2
    type: tmpfs
    options: rw,size=20M
```
