### ISSUE TITLE
Refactor the container_dir settings. Provide a way to configure multiple individual repositories

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#174]
Currently the keys are referenced in the configuration with a directory. The runtime searches for files within that directory which is not intuitive. 

The configuration should look like this:

```toml
debug = true
console_address = "localhost:4200"
key = "examples/keys/north.pub"
container_uid = 1000
container_gid = 1000

[directories]
container_dirs = [ "target/north/registry" ]
run_dir = "target/north/run"
data_dir = "target/north/data"
```

**Comment by bzld** [comment]
The `signature.yaml` contains a `key:` field to support having different signing keys between NPKs (owned by different parties for example).
That's why the folder approach was used to search for the right one to use.

Maybe we don't need this flexbility.

In case we _do_ want to keep it, we should rather have a key name -> key file mapping in configuration? Like:
```toml
[keys]
north = "examples/keys/north.pub"
external = "examples/keys/external.pub"
```
