### ISSUE TITLE
Resource README is out of date with respect to mounts

### ISSUE THREAD

**Issue by pclesr** [esrlabs/northstar#186]
The sample manifest in the readme says:
```
resources:
  - name: ferris
    version: 0.0.2
    dir: /
    mountpoint: /bin
  - name: hello_message
    version: 0.1.2
    dir: /
    mountpoint: /message
```

But the actual manifest uses a different syntax

```
mounts:
    /lib:
      host: /lib
    /lib64:
      host: /lib64
    /system:
      host: /system
    /bin:
      resource: ferris:0.0.2
    /message:
      resource: hello_message:0.1.2
# Pass the filename with the hello message
args:
  - /message/hello
```
