### ISSUE TITLE
Docs of northstar crate are hidden by main

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#394]
The `main` crate hides documentation for the `northstar` crate because it declares 

```toml
[[bin]]
name = "northstar"
path = "src/main.rs"
```

A `cargo doc` should generate doc also for the crate `northstar`.
