### ISSUE TITLE
Semantic versioning for resource dependencies

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#567]
Today a resource is addressed by it's exact name and version. Consider lifting this restriction to a resource version that fulfils the required version with respect to semantic versioning e.g

```yaml
  /bin:
    type: resource
    name: somename
    version: >=0.1.1
    dir: /
```

or

```yaml
  /bin:
    type: resource
    name: somename
    version: 1.1
    dir: /
```

Calculating semver checks is hard but again we can stand on the shoulders of giants: https://crates.io/crates/semver
