### ISSUE TITLE
Cargo npk subcommand

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#596]
Think about implementing a cargo subcommand for building npks from Rust crates. e.g

```sh
cargo npk --bin <bin> --release --root res/root --manifest res/manifest.yaml ....
```

The manifest could also be merged with the cargo manifest

```toml
[package]
name = "hello-world"
version = "0.1.0"
authors = ["ESRLabs"]
edition = "2021"
license = "Apache-2.0"


[package.metadata.npk]
version = "0.0.1"
init = "/hello-world"
uid = 1000
gid = 1000
```

Consider using [xtask](https://github.com/matklad/cargo-xtask) in order to get cross build with the support of `cross`.

See [cargo-deb](https://github.com/kornelski/cargo-deb) as reference.
