### ISSUE TITLE
Console permissions shall be repository specific

### ISSUE THREAD

**Issue by flxo** [esrlabs/northstar#822]
The console permissions are global. This conflicts with the need to grant permissions to e.g `kill` a container that is from our or multiple  *specific* repositories. E.g allow a system health monitor to kill unimportant applications but do not grant the right to kill essential system services which aren't updatable anyways. 

This is very likely a manifest format change.

**Comment by flxo** [comment]
Could look like:
```yaml
console:
  permissions:
    - ident
    - notifications
    - !inspect
      targets:
        - !repository default
        - !repository asdf
        - !container console
    - kill
    - list
 ```
